/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baith1;

import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class TableSV extends javax.swing.JFrame {
    ArrayList<SinhVienMatMa> ds=new ArrayList();
    ArrayList<SinhVienHTTT> ds2=new ArrayList();
    /**
     * Creates new form TableSV
     */
    public TableSV() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
//        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        txtdonvi.setEnabled(false);
        txthocphi.setEnabled(false);
        txtluong.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmasv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdiemtb = new javax.swing.JTextField();
        gtinh = new javax.swing.JComboBox<>();
        svhttt = new javax.swing.JRadioButton();
        svmm = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtluong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdonvi = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        Luu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txthocphi = new javax.swing.JTextField();
        Nhap = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vũ Đình Đức");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Quản Lý Sinh Viên ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Họ Tên");

        txthoten.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã SV");

        txtmasv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ngày Sinh");

        txtngaysinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Giới Tính");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Điểm Tb");

        txtdiemtb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        gtinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gtinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam ", "Nữ", "Khác" }));
        gtinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtinhActionPerformed(evt);
            }
        });

        buttonGroup1.add(svhttt);
        svhttt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        svhttt.setText("Sinh Viên HTTT");
        svhttt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svhtttActionPerformed(evt);
            }
        });

        buttonGroup1.add(svmm);
        svmm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        svmm.setText("Sinh Viên Mật Mã");
        svmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svmmActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Lương");

        txtluong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Đơn Vị ");

        txtdonvi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Luu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Luu.setText("LƯU");
        Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuuActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Học Phí ");

        txthocphi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Nhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nhap.setText("NHẬP");
        Nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGap(2, 2, 2)))
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdiemtb, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gtinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 30, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addComponent(txtdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txthocphi, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(svhttt)
                        .addGap(18, 18, 18)
                        .addComponent(svmm))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Nhap)
                        .addGap(78, 78, 78)
                        .addComponent(Reset)
                        .addGap(73, 73, 73)
                        .addComponent(Luu)))
                .addGap(239, 239, 239))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gtinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdiemtb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svhttt)
                    .addComponent(svmm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10)
                        .addGap(37, 150, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthocphi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Reset)
                            .addComponent(Luu)
                            .addComponent(Nhap))
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gtinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtinhActionPerformed

    private void svmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svmmActionPerformed
               txtdonvi.setEnabled(true);
        txthocphi.setEnabled(false);
        txtluong.setEnabled(true); // TODO add your handling code here:
    }//GEN-LAST:event_svmmActionPerformed

    private void svhtttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svhtttActionPerformed
        txtdonvi.setEnabled(false);
        txthocphi.setEnabled(true);
        txtluong.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_svhtttActionPerformed

    private void NhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapActionPerformed
if (svmm.isSelected())
        {
        SinhVienMatMa svmmn=new SinhVienMatMa();
        svmmn.setMaSv(txtmasv.getText());
        svmmn.setHoTen(txthoten.getText());
        svmmn.setGioiTinh(gtinh.getSelectedItem().toString());
            SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
        try {
            svmmn.setNgaySinh(sdf.parse(txtngaysinh.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(TableSV.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        svmmn.setDiemTb(Float.parseFloat(txtdiemtb.getText()));
        try{
        svmmn.setDonvi(txtdonvi.getText());
        svmmn.setLuong(txtluong.getText());
        ds.add(svmmn);
        for (SinhVienMatMa x :ds)
            {
                x.hienThi();
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
            JOptionPane.showMessageDialog(rootPane, "Them thanh cong");
        }else if(svhttt.isSelected())
        {
            SinhVienHTTT svhtn=new SinhVienHTTT();
            svhtn.setMaSv(txtmasv.getText());
            svhtn.setHoTen(txthoten.getText());
            SimpleDateFormat sdf=new SimpleDateFormat("dd/mm/yyyy");
            try {
            svhtn.setNgaySinh(sdf.parse(txtngaysinh.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(TableSV.class.getName()).log(Level.SEVERE, null, ex);
            }
            svhtn.setGioiTinh(gtinh.getSelectedItem().toString());
            svhtn.setHocPhi(txthocphi.getText());
            ds2.add(svhtn);
            for (SinhVienHTTT x :ds2)
            {
                x.hienThi();
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Ban phai chon sinh vien");
                
                }  
    }//GEN-LAST:event_NhapActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        txtmasv.setText("");
        txthoten.setText("");
        txtngaysinh.setText("");
        gtinh.setSelectedItem("Nam");
        txtdonvi.setText("");
        txthocphi.setText("");
        txtluong.setText("");
        txtdiemtb.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuuActionPerformed
      if(svmm.isSelected())
      {
        try {
            FileOutputStream fos=new FileOutputStream("svmatma.dat");
            ObjectOutputStream oos=new ObjectOutputStream(fos);
            oos.writeObject(ds);
            
            JOptionPane.showMessageDialog(rootPane, "Luu Thanh cong");
            oos.close();
            fos.close();
        } catch (Exception e) {
            e.printStackTrace();
        }}
      else if (svhttt.isSelected())
      {
          try {
              FileOutputStream fos=new FileOutputStream("svhtn.dat");
              OutputStreamWriter osw=new OutputStreamWriter(fos);
              BufferedWriter bw =new BufferedWriter(osw);
              String line="";
              for(SinhVienHTTT svhtn:ds2)
              {
                  line+=svhtn.getMaSv()+"$";
                  line+=svhtn.getHoTen()+"$";
                  line+=new SimpleDateFormat().format(svhtn.getNgaySinh());
                  line+=svhtn.getGioiTinh();
                  line+=svhtn.getDiemTb();
                  line+=svhtn.getHocPhi();
                  bw.write(line);
                  bw.newLine();
              }
              bw.close();
              fos.close();
              osw.close();
          JOptionPane.showMessageDialog(rootPane, "Luu Sinh vien ht thanh cong");
                  this.setDefaultCloseOperation(EXIT_ON_CLOSE);
          } catch (Exception e) {
          }  // TODO add your handling code here:
    }//GEN-LAST:event_LuuActionPerformed
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Luu;
    private javax.swing.JButton Nhap;
    private javax.swing.JButton Reset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> gtinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton svhttt;
    private javax.swing.JRadioButton svmm;
    private javax.swing.JTextField txtdiemtb;
    private javax.swing.JTextField txtdonvi;
    private javax.swing.JTextField txthocphi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtmasv;
    private javax.swing.JTextField txtngaysinh;
    // End of variables declaration//GEN-END:variables
}
